baseURL = 'https://example.org/'
languageCode = 'zh-CN'
title = 'Terry.Wang'

[[menus.main]]
name = 'pixwind'
url = 'http://pixwind.com'
weight = 10
target = "_blank"

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"